### ISSUE TITLE
Get distance in miles

### ISSUE THREAD

**Issue by wisdom-17** [craue/CraueGeoBundle#18]
Hi,

I've implemented bundle successfully in my Symfony (3.4) project but want to know how I can override the geo query to return miles instead of kilometres.

Appreciate any advice

**Comment by craue** [comment]
To get a result in miles, use the appropriate conversion factor, like:
`GEO_DISTANCE(:latOrigin, :lngOrigin, :latDestination, :lngDestination) * 0.6213712`

**Comment by wisdom-17** [comment]
Thanks @craue, appreciate the help and work you've put into this bundle.

Now that you've provided the solution and seeing how simple it is, I feel silly for not figuring it out myself.
