### ISSUE TITLE
incorrect distance calculation?

### ISSUE THREAD

**Issue by yivi** [craue/CraueGeoBundle#19]
Can't figure this one out. I apologize in advance when it turns out I was being a moron. :(

For two given points:
* Rivas Vaciamadrid, Madrid Spain: 40.3518,-3.5362
* San Sebastián de los Reyes, Madrid Spain: 40.5596,-3.6261

The generated distance query (using `GEO_DISTANCE(40.3518,-3.5362,40.5596,-3.6261)`) is:

```sql
SELECT 12742 * ASIN(SQRT(
            POWER(SIN((CAST(40.4256 AS NUMERIC) - CAST(40.5596 AS NUMERIC)) * PI() / 360), 2) +
            COS(40.4256 * PI() / 180) * COS(40.5596 * PI() / 180) *
            POWER(SIN((CAST(-3.5319 AS NUMERIC) - CAST(-3.6261 AS NUMERIC)) * PI() / 360), 2))) AS sclr_0
```

Output for the above is 16.895781163873654

But actually the distance for these two points is ~24.3:
![image](https://user-images.githubusercontent.com/1815039/121804160-4a856d00-cc45-11eb-8732-99328653ce82.png)

![image](https://user-images.githubusercontent.com/1815039/121804163-4e18f400-cc45-11eb-9773-8bf3c1c4ac19.png)

Caught this because the 7km difference is enough to show incorrect results in the query I'm working on.

Find hard to believe this is actually a bug on the package, yet I cannot see what else is going on here.

**Comment by yivi** [comment]
As an additional data-point, tried installing https://www.postgresql.org/docs/12/earthdistance.html, and got `24353.442403726403` when running:

```sql
SELECT earth_distance(ll_to_earth(40.5596,-3.6261), ll_to_earth(40.3518,-3.5362));
```

**Comment by craue** [comment]
Putting these locations in a test (like [here](https://github.com/craue/CraueGeoBundle/blob/95bbedcf58e5eca04e4e1bff2a9376504ed9d109/Tests/Doctrine/Query/Mysql/GeoDistanceTest.php#L60)) I get a distance of about 24.326 km, so this seems perfectly fine.

**Comment by yivi** [comment]
I'm sorry, it's obviously something on my end. I'll try to figure it out later today.

My apologies, and thanks.
