### ISSUE TITLE
How to ignore "craue_geo_postalcode" table creation ?

### ISSUE THREAD

**Issue by jcrombez** [craue/CraueGeoBundle#8]
Is there a way to ignore the "craue_geo_postalcode" table creation ?

**Comment by craue** [comment]
You could disable auto mapping and only enable mappings for all other bundles. But why do you want/need to do this?

**Comment by jcrombez** [comment]
Simply because i don't use the postal code feature.
Loosing auto mapping isn't very nice...

**Comment by JHGitty** [comment]
@craue Could you please do this? I like to use this bundle but without postal code feature.

**Comment by craue** [comment]
Done in the referenced PR. Please verify that it's working as expected.

**Comment by jcrombez** [comment]
Sorry i'm no longer working on the project using this.
